In [483]:
import pandas as pd
import numpy as np
import datetime as dt
import random

random.seed(42)
np.random.seed(42)

In [484]:
ads=pd.read_csv('ad_spend_daily.csv')
customers=pd.read_csv('customer_journeys.csv')

In [485]:
new_ads_df=ads.copy()
customers_copy=customers.copy()

In [486]:
new_ads_df.head()

,date,channel,campaign_name,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective
0,2022-01-01,Google Search,Seasonal_Sale_Jan2022,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty
1,2022-01-01,Google Display,Loyalty_Jan2022,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch
2,2022-01-01,Meta Facebook,Brand_Awareness_Jan2022,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting
3,2022-01-01,Meta Instagram,Brand_Awareness_Jan2022,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,Loyalty_Jan2022,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty

In [487]:
new_ads_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10960 entries, 0 to 10959
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                10960 non-null  object
 1   channel             10960 non-null  object
 2   campaign_name       10960 non-null  object
 3   spend_KES           10960 non-null  float64
 4   impressions         10960 non-null  int64
 5   clicks              10960 non-null  int64
 6   conversions         10960 non-null  int64
 7   revenue_KES         10960 non-null  float64
 8   ctr                 10960 non-null  float64
 9   cpc_KES             10960 non-null  float64
 10  roas                10960 non-null  float64
 11  target_region       10960 non-null  object
 12  campaign_objective  10960 non-null  object
dtypes: float64(5), int64(3), object(5)
memory usage: 1.1+ MB

In [488]:
new_ads_df['date']=pd.to_datetime(new_ads_df['date'])

In [489]:
new_ads_df['campaign_name'].nunique()

216

In [490]:
new_ads_df['campaign_name_clean']=new_ads_df['campaign_name'].replace('-','_')
new_ads_df['campaign_name_clean']=new_ads_df['campaign_name'].replace(' ','_')

In [491]:
new_ads_df['campaign_name_clean']=new_ads_df['campaign_name'].str.strip().str.lower()

In [492]:
new_ads_df['campaign_name_clean'].nunique()

216

In [493]:
new_ads_df.head()

,date,channel,campaign_name,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name_clean
0,2022-01-01,Google Search,Seasonal_Sale_Jan2022,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,seasonal_sale_jan2022
1,2022-01-01,Google Display,Loyalty_Jan2022,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,loyalty_jan2022
2,2022-01-01,Meta Facebook,Brand_Awareness_Jan2022,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,brand_awareness_jan2022
3,2022-01-01,Meta Instagram,Brand_Awareness_Jan2022,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,brand_awareness_jan2022
4,2022-01-01,Email Campaign,Loyalty_Jan2022,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,loyalty_jan2022

In [494]:
new_ads_df.head()

,date,channel,campaign_name,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name_clean
0,2022-01-01,Google Search,Seasonal_Sale_Jan2022,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,seasonal_sale_jan2022
1,2022-01-01,Google Display,Loyalty_Jan2022,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,loyalty_jan2022
2,2022-01-01,Meta Facebook,Brand_Awareness_Jan2022,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,brand_awareness_jan2022
3,2022-01-01,Meta Instagram,Brand_Awareness_Jan2022,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,brand_awareness_jan2022
4,2022-01-01,Email Campaign,Loyalty_Jan2022,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,loyalty_jan2022

In [495]:
new_ads_df['date_mnth']=new_ads_df['date'].dt.month_name()
new_ads_df['date_yr']=new_ads_df['date'].dt.year
yrs=new_ads_df['date_yr']

In [496]:
new_ads_df['new_names']=new_ads_df['channel'] + '_' + new_ads_df['campaign_objective']

In [497]:
new_ads_df['new_names']=new_ads_df['new_names'] + '_' + new_ads_df['date_mnth']

In [498]:
new_ads_df['new_names']=new_ads_df['new_names'] + '_' + [f"{i}" for i in yrs]

In [499]:
new_ads_df.head()

,date,channel,campaign_name,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name_clean,date_mnth,date_yr,new_names
0,2022-01-01,Google Search,Seasonal_Sale_Jan2022,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,seasonal_sale_jan2022,January,2022,Google Search_Loyalty_January_2022
1,2022-01-01,Google Display,Loyalty_Jan2022,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,loyalty_jan2022,January,2022,Google Display_Product Launch_January_2022
2,2022-01-01,Meta Facebook,Brand_Awareness_Jan2022,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,brand_awareness_jan2022,January,2022,Meta Facebook_Retargeting_January_2022
3,2022-01-01,Meta Instagram,Brand_Awareness_Jan2022,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,brand_awareness_jan2022,January,2022,Meta Instagram_Lead Generation_January_2022
4,2022-01-01,Email Campaign,Loyalty_Jan2022,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,loyalty_jan2022,January,2022,Email Campaign_Loyalty_January_2022

In [500]:
new_ads_df=new_ads_df.drop(columns=['campaign_name','campaign_name_clean','date_mnth','date_yr'])

In [501]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,new_names
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,Google Search_Loyalty_January_2022
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,Google Display_Product Launch_January_2022
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,Meta Facebook_Retargeting_January_2022
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,Meta Instagram_Lead Generation_January_2022
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,Email Campaign_Loyalty_January_2022

In [502]:
new_ads_df['new_names']=new_ads_df['new_names'].str.replace(' ','')

In [503]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,new_names
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,GoogleSearch_Loyalty_January_2022
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,GoogleDisplay_ProductLaunch_January_2022
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,MetaFacebook_Retargeting_January_2022
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,MetaInstagram_LeadGeneration_January_2022
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,EmailCampaign_Loyalty_January_2022

In [504]:
new_ads_df=new_ads_df.rename(columns={'new_names': 'campaign_name'})

In [505]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,GoogleSearch_Loyalty_January_2022
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,GoogleDisplay_ProductLaunch_January_2022
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,MetaFacebook_Retargeting_January_2022
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,MetaInstagram_LeadGeneration_January_2022
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,EmailCampaign_Loyalty_January_2022

In [506]:
new_ads_df['campaign_name'].nunique()

2153

**Customers_data**

In [507]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
0,JRN0000001,CUS014969,1,1,Google Search,NaN,2022-06-28 11:51:05,1,1,0,0.0,0
1,JRN0000002,CUS000530,1,1,Influencer,NaN,2023-05-14 08:09:01,1,1,0,0.0,0
2,JRN0000003,CUS012098,1,6,Email Campaign,NaN,2023-08-31 04:12:05,1,0,0,0.0,0
3,JRN0000003,CUS012098,2,6,YouTube Ads,Email Campaign,2023-09-01 06:12:05,0,0,0,0.0,0
4,JRN0000003,CUS012098,3,6,Meta Facebook,YouTube Ads,2023-09-04 22:12:05,0,0,0,0.0,0

In [508]:
customers_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270563 entries, 0 to 270562
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   journey_id            270563 non-null  object
 1   customer_id           270563 non-null  object
 2   touchpoint_order      270563 non-null  int64
 3   touchpoint_total      270563 non-null  int64
 4   channel               270563 non-null  object
 5   previous_channel      210563 non-null  object
 6   touch_timestamp       270563 non-null  object
 7   is_first_touch        270563 non-null  int64
 8   is_last_touch         270563 non-null  int64
 9   converted             270563 non-null  int64
 10  conversion_value_KES  270563 non-null  float64
 11  duplicate_conversion  270563 non-null  int64
dtypes: float64(1), int64(6), object(5)
memory usage: 24.8+ MB

In [509]:
customers_copy['previous_channel']=customers_copy['previous_channel'].fillna('N/A')

In [510]:
customers_copy.isnull().sum()

journey_id              0
customer_id             0
touchpoint_order        0
touchpoint_total        0
channel                 0
previous_channel        0
touch_timestamp         0
is_first_touch          0
is_last_touch           0
converted               0
conversion_value_KES    0
duplicate_conversion    0
dtype: int64

In [511]:
customers_copy.duplicated().sum()

np.int64(0)

In [512]:
customers_copy[customers_copy['duplicate_conversion']==1].sort_values(by='customer_id')

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
238196,JRN0052872,CUS000008,8,8,Email Campaign,Meta Facebook,2022-03-30 12:29:54,0,1,1,39591.24,1
18925,JRN0004208,CUS000035,1,1,Meta Facebook,N/A,2022-11-23 16:24:41,1,1,1,29580.83,1
181387,JRN0040229,CUS000132,5,5,TikTok Ads,Organic SEO,2022-11-01 00:12:34,0,1,1,35180.98,1
98758,JRN0021862,CUS000188,3,3,TikTok Ads,YouTube Ads,2022-05-31 03:20:10,0,1,1,35032.41,1
252734,JRN0056077,CUS000199,7,7,Google Search,Google Display,2024-03-07 12:14:24,0,1,1,38028.06,1
...,...,...,...,...,...,...,...,...,...,...,...,...
11886,JRN0002641,CUS014858,4,4,TikTok Ads,Meta Instagram,2022-07-06 23:30:52,0,1,1,49221.07,1
214051,JRN0047509,CUS014875,2,2,Email Campaign,Email Campaign,2022-02-27 13:44:59,0,1,1,16899.21,1
161999,JRN0035932,CUS014923,2,2,Email Campaign,Google Display,2022-02-08 13:57:12,0,1,1,5320.76,1
35113,JRN0007785,CUS014933,8,8,Google Display,TikTok Ads,2024-04-17 12:41:29,0,1,1,29270.00,1
15281,JRN0003404,CUS014964,8,8,YouTube Ads,Influencer,2023-01-22 19:11:46,0,1,1,2547.65,1

In [513]:
customers_copy['touch_timestamp']=pd.to_datetime(customers_copy['touch_timestamp'])

In [514]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
0,JRN0000001,CUS014969,1,1,Google Search,N/A,2022-06-28 11:51:05,1,1,0,0.0,0
1,JRN0000002,CUS000530,1,1,Influencer,N/A,2023-05-14 08:09:01,1,1,0,0.0,0
2,JRN0000003,CUS012098,1,6,Email Campaign,N/A,2023-08-31 04:12:05,1,0,0,0.0,0
3,JRN0000003,CUS012098,2,6,YouTube Ads,Email Campaign,2023-09-01 06:12:05,0,0,0,0.0,0
4,JRN0000003,CUS012098,3,6,Meta Facebook,YouTube Ads,2023-09-04 22:12:05,0,0,0,0.0,0

In [515]:
customers_copy=customers_copy.sort_values(by=['touch_timestamp','customer_id'])

In [516]:
customers_copy['touch_timestamp'].duplicated()

32117     False
129395    False
84252     False
30762     False
247173    False
          ...
98682     False
64848     False
188616    False
95962     False
118247    False
Name: touch_timestamp, Length: 270563, dtype: bool

In [517]:
customers_copy['touch_timestamp'].duplicated().sum()

np.int64(2138)

In [518]:
customers_copy[ customers_copy ['touch_timestamp'].duplicated(keep=False) ]

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
129396,JRN0028671,CUS008598,2,6,Meta Instagram,Organic SEO,2022-01-02 21:54:17,0,0,0,0.0,0
129400,JRN0028671,CUS008598,6,6,Meta Facebook,Meta Facebook,2022-01-02 21:54:17,0,1,0,0.0,0
32119,JRN0007131,CUS009771,3,5,Influencer,Google Display,2022-01-03 06:23:51,0,0,0,0.0,0
32120,JRN0007131,CUS009771,4,5,Influencer,Influencer,2022-01-03 06:23:51,0,0,0,0.0,0
89286,JRN0019764,CUS012744,2,8,Influencer,SMS,2022-01-04 17:09:04,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
249686,JRN0055405,CUS000051,7,7,TikTok Ads,YouTube Ads,2024-12-31 22:24:18,0,1,0,0.0,0
208417,JRN0046246,CUS003748,3,6,Email Campaign,SMS,2025-01-01 09:22:16,0,0,0,0.0,0
208418,JRN0046246,CUS003748,4,6,TikTok Ads,Email Campaign,2025-01-01 09:22:16,0,0,0,0.0,0
95960,JRN0021248,CUS002892,6,8,Google Search,Google Display,2025-01-04 08:46:18,0,0,0,0.0,0
95961,JRN0021248,CUS002892,7,8,Influencer,Google Search,2025-01-04 08:46:18,0,0,0,0.0,0

In [519]:
customers_copy ['duplicate_conversion']=np.where(customers_copy ['touch_timestamp'].duplicated(),1 , customers_copy ['duplicate_conversion'])

In [520]:
customers_copy [ customers_copy ['touch_timestamp'].duplicated(keep=False) ]

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
129396,JRN0028671,CUS008598,2,6,Meta Instagram,Organic SEO,2022-01-02 21:54:17,0,0,0,0.0,0
129400,JRN0028671,CUS008598,6,6,Meta Facebook,Meta Facebook,2022-01-02 21:54:17,0,1,0,0.0,1
32119,JRN0007131,CUS009771,3,5,Influencer,Google Display,2022-01-03 06:23:51,0,0,0,0.0,0
32120,JRN0007131,CUS009771,4,5,Influencer,Influencer,2022-01-03 06:23:51,0,0,0,0.0,1
89286,JRN0019764,CUS012744,2,8,Influencer,SMS,2022-01-04 17:09:04,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
249686,JRN0055405,CUS000051,7,7,TikTok Ads,YouTube Ads,2024-12-31 22:24:18,0,1,0,0.0,1
208417,JRN0046246,CUS003748,3,6,Email Campaign,SMS,2025-01-01 09:22:16,0,0,0,0.0,0
208418,JRN0046246,CUS003748,4,6,TikTok Ads,Email Campaign,2025-01-01 09:22:16,0,0,0,0.0,1
95960,JRN0021248,CUS002892,6,8,Google Search,Google Display,2025-01-04 08:46:18,0,0,0,0.0,0
95961,JRN0021248,CUS002892,7,8,Influencer,Google Search,2025-01-04 08:46:18,0,0,0,0.0,1

In [521]:
len (customers_copy [ customers_copy ['duplicate_conversion']==1 ])

2545

**Got all duplicate entries; dropping them**

In [522]:
len(customers_copy )

270563

In [523]:
non_duplicate_conv= customers_copy [ customers_copy ['duplicate_conversion']==0 ]

In [524]:
len(non_duplicate_conv)

268018

In [525]:
customers_copy = customers_copy [ customers_copy ['duplicate_conversion']==0 ]

In [526]:
len(customers_copy [ customers_copy ['duplicate_conversion']==0 ])

268018

In [527]:
deduplication_rate=len(customers_copy) / len(non_duplicate_conv)

In [528]:
deduplication_rate

1.0

**Attribution window Definition**

In [529]:
customers_copy=customers_copy.sort_values(by=['customer_id','touch_timestamp'])
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0

In [530]:
attr_window=customers_copy.groupby('customer_id').agg({
    'customer_id': 'count',
    'touch_timestamp': ['min','max'],
    'conversion_value_KES': 'sum'
})

In [531]:
attr_window

            customer_id     touch_timestamp                      \
                  count                 min                 max
customer_id
CUS000001             4 2024-11-04 04:51:08 2024-11-07 04:51:08
CUS000002            11 2022-09-16 14:50:21 2024-04-30 09:13:47
CUS000003            21 2023-06-16 15:49:15 2024-12-18 08:39:28
CUS000004            15 2022-01-19 09:58:39 2024-10-02 20:50:14
CUS000005            27 2022-01-22 06:43:40 2024-10-14 09:11:23
...                 ...                 ...                 ...
CUS014996            16 2023-06-23 15:45:08 2024-10-23 03:21:32
CUS014997             9 2022-07-27 09:56:16 2024-10-18 12:03:50
CUS014998            26 2022-03-01 01:37:18 2024-12-01 19:03:54
CUS014999            15 2023-04-17 16:43:35 2024-12-23 14:02:49
CUS015000            23 2022-03-07 06:16:33 2024-11-27 23:41:56

            conversion_value_KES
                             sum
customer_id
CUS000001                   0.00
CUS000002                   0.00
CUS000003               17678.81
CUS000004                1078.46
CUS000005                   0.00
...                          ...
CUS014996               23311.36
CUS014997                   0.00
CUS014998                   0.00
CUS014999                   0.00
CUS015000                   0.00

[14732 rows x 4 columns]

In [532]:
attr_window['window_period']=(attr_window['touch_timestamp']['max']- attr_window['touch_timestamp']['min']).dt.days

In [533]:
attr_window

            customer_id     touch_timestamp                      \
                  count                 min                 max
customer_id
CUS000001             4 2024-11-04 04:51:08 2024-11-07 04:51:08
CUS000002            11 2022-09-16 14:50:21 2024-04-30 09:13:47
CUS000003            21 2023-06-16 15:49:15 2024-12-18 08:39:28
CUS000004            15 2022-01-19 09:58:39 2024-10-02 20:50:14
CUS000005            27 2022-01-22 06:43:40 2024-10-14 09:11:23
...                 ...                 ...                 ...
CUS014996            16 2023-06-23 15:45:08 2024-10-23 03:21:32
CUS014997             9 2022-07-27 09:56:16 2024-10-18 12:03:50
CUS014998            26 2022-03-01 01:37:18 2024-12-01 19:03:54
CUS014999            15 2023-04-17 16:43:35 2024-12-23 14:02:49
CUS015000            23 2022-03-07 06:16:33 2024-11-27 23:41:56

            conversion_value_KES window_period
                             sum
customer_id
CUS000001                   0.00             3
CUS000002                   0.00           591
CUS000003               17678.81           550
CUS000004                1078.46           987
CUS000005                   0.00           996
...                          ...           ...
CUS014996               23311.36           487
CUS014997                   0.00           814
CUS014998                   0.00          1006
CUS014999                   0.00           615
CUS015000                   0.00           996

[14732 rows x 5 columns]

In [534]:
customers_copy['conversions_window_days']=customers_copy['customer_id'].map(attr_window['window_period'])

In [535]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion,conversions_window_days
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591

In [536]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion,conversions_window_days
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591

**Getting the conversion_value of customers in each day**

In [537]:
customers_copy['touch_timestamp_day']=customers_copy['touch_timestamp'].dt.floor('d')

In [538]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion,conversions_window_days,touch_timestamp_day
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3,2024-11-04
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3,2024-11-06
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3,2024-11-06
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3,2024-11-07
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591,2022-09-16

In [539]:
customers_conversion_values_channel_day=customers_copy.groupby( ['touch_timestamp_day','channel'] )['conversion_value_KES'].sum().reset_index()

In [540]:
customers_conversion_values_channel_day=customers_conversion_values_channel_day.rename(columns={'touch_timestamp_day': 'date','conversion_value_KES': 'revenue_KSH'})

**There is a lot of discrepancies btn revenue from ads data and revenue from customers data**

In [541]:
new_ads_df=pd.merge(new_ads_df,customers_conversion_values_channel_day, on=['date','channel'],how='left')

In [542]:
new_ads_df['channel_campaign_objective']=new_ads_df['channel'] + '_' + new_ads_df['campaign_objective']
new_ads_df['channel_campaign_objective']=new_ads_df['channel_campaign_objective'].str.replace(' ','')

In [543]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name,revenue_KSH,channel_campaign_objective
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,GoogleSearch_Loyalty_January_2022,30580.72,GoogleSearch_Loyalty
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,GoogleDisplay_ProductLaunch_January_2022,0.00,GoogleDisplay_ProductLaunch
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,MetaFacebook_Retargeting_January_2022,22153.08,MetaFacebook_Retargeting
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,MetaInstagram_LeadGeneration_January_2022,0.00,MetaInstagram_LeadGeneration
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,EmailCampaign_Loyalty_January_2022,0.00,EmailCampaign_Loyalty

In [544]:
customers_conversion_values_channel_day

            date         channel  revenue_KSH
0     2022-01-01  Email Campaign         0.00
1     2022-01-01  Google Display         0.00
2     2022-01-01   Google Search     30580.72
3     2022-01-01      Influencer         0.00
4     2022-01-01   Meta Facebook     22153.08
...          ...             ...          ...
11088 2025-01-16             SMS         0.00
11089 2025-01-17  Google Display         0.00
11090 2025-01-18      Influencer         0.00
11091 2025-01-18      TikTok Ads         0.00
11092 2025-01-20     YouTube Ads         0.00

[11093 rows x 3 columns]

In [545]:
customer_clicks=customers_copy.groupby(['touch_timestamp_day','channel'])['converted'].count().reset_index()
customer_clicks=customer_clicks.rename(columns={'converted': 'new_clicks', 'touch_timestamp_day': 'date'})
customer_clicks

            date         channel  new_clicks
0     2022-01-01  Email Campaign           6
1     2022-01-01  Google Display           8
2     2022-01-01   Google Search           4
3     2022-01-01      Influencer           7
4     2022-01-01   Meta Facebook           7
...          ...             ...         ...
11088 2025-01-16             SMS           2
11089 2025-01-17  Google Display           1
11090 2025-01-18      Influencer           1
11091 2025-01-18      TikTok Ads           1
11092 2025-01-20     YouTube Ads           1

[11093 rows x 3 columns]

In [546]:
customer_conversions=customers_copy.groupby(['touch_timestamp_day','channel'])['converted'].sum().reset_index()
customer_conversions=customer_conversions.rename(columns={'converted': 'new_conversions','touch_timestamp_day': 'date'})
customer_conversions

            date         channel  new_conversions
0     2022-01-01  Email Campaign                0
1     2022-01-01  Google Display                0
2     2022-01-01   Google Search                1
3     2022-01-01      Influencer                0
4     2022-01-01   Meta Facebook                1
...          ...             ...              ...
11088 2025-01-16             SMS                0
11089 2025-01-17  Google Display                0
11090 2025-01-18      Influencer                0
11091 2025-01-18      TikTok Ads                0
11092 2025-01-20     YouTube Ads                0

[11093 rows x 3 columns]

In [547]:
new_ads_df=pd.merge(new_ads_df,customer_clicks, on=['date','channel'],how='left')

In [548]:
new_ads_df=pd.merge(new_ads_df,customer_conversions, on=['date','channel'],how='left')

In [549]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective,campaign_name,revenue_KSH,channel_campaign_objective,new_clicks,new_conversions
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty,GoogleSearch_Loyalty_January_2022,30580.72,GoogleSearch_Loyalty,4,1
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch,GoogleDisplay_ProductLaunch_January_2022,0.00,GoogleDisplay_ProductLaunch,8,0
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting,MetaFacebook_Retargeting_January_2022,22153.08,MetaFacebook_Retargeting,7,1
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation,MetaInstagram_LeadGeneration_January_2022,0.00,MetaInstagram_LeadGeneration,8,0
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty,EmailCampaign_Loyalty_January_2022,0.00,EmailCampaign_Loyalty,6,0

In [550]:
new_ads_df['spend_KES'].min()

np.float64(3030.27)

**Computing new `spend_KES, impressions, ctr, cpc, roas`**

In [551]:
new_ads_df['new_spend_KES']=np.random.randint(new_ads_df['spend_KES'].min(),10000,size=len(new_ads_df))

In [552]:
new_ads_df['new_impressions']= np.random.randint(new_ads_df['new_spend_KES'] , new_ads_df['new_spend_KES']* 1.1)

In [553]:
new_ads_df['new_ctr']= ( (new_ads_df['new_clicks']/ new_ads_df['new_impressions']) * 100 )

In [554]:
new_ads_df['new_cpc_KES']= (new_ads_df['new_spend_KES']/ new_ads_df['new_clicks'])

In [555]:
new_ads_df['new_roas']= (new_ads_df['revenue_KSH']/ new_ads_df['new_spend_KES'])

In [556]:
new_ads_df.head()

,date,channel,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,...,campaign_name,revenue_KSH,channel_campaign_objective,new_clicks,new_conversions,new_spend_KES,new_impressions,new_ctr,new_cpc_KES,new_roas
0,2022-01-01,Google Search,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,...,GoogleSearch_Loyalty_January_2022,30580.72,GoogleSearch_Loyalty,4,1,3890,4133,0.096782,972.500000,7.861368
1,2022-01-01,Google Display,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,...,GoogleDisplay_ProductLaunch_January_2022,0.00,GoogleDisplay_ProductLaunch,8,0,8420,8505,0.094062,1052.500000,0.000000
2,2022-01-01,Meta Facebook,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,...,MetaFacebook_Retargeting_January_2022,22153.08,MetaFacebook_Retargeting,7,1,8256,8670,0.080738,1179.428571,2.683270
3,2022-01-01,Meta Instagram,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,...,MetaInstagram_LeadGeneration_January_2022,0.00,MetaInstagram_LeadGeneration,8,0,8221,8614,0.092872,1027.625000,0.000000
4,2022-01-01,Email Campaign,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,...,EmailCampaign_Loyalty_January_2022,0.00,EmailCampaign_Loyalty,6,0,6802,7434,0.080710,1133.666667,0.000000

In [557]:
new_ads_df['new_spend_KES'].value_counts()

new_spend_KES
6884    8
7810    8
6749    8
7554    8
8006    7
       ..
3364    1
4389    1
8765    1
3242    1
4688    1
Name: count, Length: 5470, dtype: int64

**Re-arranging the order of column names**

In [558]:
new_order_cols_list=['date', 'channel','channel_campaign_objective', 'campaign_name', 'new_spend_KES', 'new_impressions', 'new_clicks', 'new_conversions', 'revenue_KSH', 'new_ctr', 'new_cpc_KES', 'new_roas', 'target_region', 'campaign_objective']
new_ads_df=new_ads_df.reindex(columns=new_order_cols_list)
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty

In [559]:
new_ads_df.shape[0]

10960

In [560]:
len(new_ads_df[new_ads_df['new_roas'] < 1])

4801

In [561]:
len(new_ads_df[new_ads_df['new_roas'] ==0])

4320

**Feature Engineering**

In [562]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty

In [563]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion,conversions_window_days,touch_timestamp_day
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3,2024-11-04
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3,2024-11-06
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3,2024-11-06
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3,2024-11-07
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591,2022-09-16

In [564]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion,conversions_window_days,touch_timestamp_day
28806,JRN0006398,CUS000001,1,4,YouTube Ads,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3,2024-11-04
28807,JRN0006398,CUS000001,2,4,Google Search,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3,2024-11-06
28808,JRN0006398,CUS000001,3,4,TikTok Ads,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3,2024-11-06
28809,JRN0006398,CUS000001,4,4,YouTube Ads,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3,2024-11-07
30595,JRN0006793,CUS000002,1,3,Meta Instagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591,2022-09-16

In [565]:
#Each channel name to be one name....
customers_copy['channel']=customers_copy['channel'].str.replace(' ','' ,regex=True)

In [566]:
#getting all channels_journey for the customer...
customers_journey_path=customers_copy.groupby(['customer_id'])['channel'].agg(list).reset_index()
customers_journey_path

      customer_id                                            channel
0       CUS000001  [YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]
1       CUS000002  [MetaInstagram, OrganicSEO, MetaFacebook, Emai...
2       CUS000003  [TikTokAds, YouTubeAds, EmailCampaign, SMS, Em...
3       CUS000004  [GoogleSearch, SMS, MetaFacebook, MetaInstagra...
4       CUS000005  [MetaInstagram, GoogleSearch, OrganicSEO, Meta...
...           ...                                                ...
14727   CUS014996  [GoogleDisplay, GoogleDisplay, MetaInstagram, ...
14728   CUS014997  [GoogleDisplay, EmailCampaign, GoogleDisplay, ...
14729   CUS014998  [YouTubeAds, Influencer, YouTubeAds, OrganicSE...
14730   CUS014999  [SMS, MetaFacebook, YouTubeAds, GoogleDisplay,...
14731   CUS015000  [OrganicSEO, EmailCampaign, MetaFacebook, SMS,...

[14732 rows x 2 columns]

In [567]:
#getting if the customer converted(conversion; no_conversion)
conversion_flag = customers_copy.groupby('customer_id')['converted'].max().reset_index()

customers_journey_path = customers_journey_path.merge(conversion_flag, on='customer_id')

In [568]:
customers_journey_path=customers_journey_path.rename(columns={'channel':'journey_path'})

In [569]:
customers_journey_path

,customer_id,journey_path,converted
0,CUS000001,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0
1,CUS000002,"[MetaInstagram, OrganicSEO, MetaFacebook, Emai...",0
2,CUS000003,"[TikTokAds, YouTubeAds, EmailCampaign, SMS, Em...",1
3,CUS000004,"[GoogleSearch, SMS, MetaFacebook, MetaInstagra...",1
4,CUS000005,"[MetaInstagram, GoogleSearch, OrganicSEO, Meta...",0
...,...,...,...
14727,CUS014996,"[GoogleDisplay, GoogleDisplay, MetaInstagram, ...",1
14728,CUS014997,"[GoogleDisplay, EmailCampaign, GoogleDisplay, ...",0
14729,CUS014998,"[YouTubeAds, Influencer, YouTubeAds, OrganicSE...",0
14730,CUS014999,"[SMS, MetaFacebook, YouTubeAds, GoogleDisplay,...",0
14731,CUS015000,"[OrganicSEO, EmailCampaign, MetaFacebook, SMS,...",0

In [570]:
#merging results to the customers_dataframe
customers_copy=pd.merge( customers_copy, customers_journey_path ,on='customer_id',how='left' )

In [571]:
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted_x,conversion_value_KES,duplicate_conversion,conversions_window_days,touch_timestamp_day,journey_path,converted_y
0,JRN0006398,CUS000001,1,4,YouTubeAds,N/A,2024-11-04 04:51:08,1,0,0,0.0,0,3,2024-11-04,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0
1,JRN0006398,CUS000001,2,4,GoogleSearch,YouTube Ads,2024-11-06 11:51:08,0,0,0,0.0,0,3,2024-11-06,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0
2,JRN0006398,CUS000001,3,4,TikTokAds,Google Search,2024-11-06 20:51:08,0,0,0,0.0,0,3,2024-11-06,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0
3,JRN0006398,CUS000001,4,4,YouTubeAds,TikTok Ads,2024-11-07 04:51:08,0,1,0,0.0,0,3,2024-11-07,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0
4,JRN0006793,CUS000002,1,3,MetaInstagram,N/A,2022-09-16 14:50:21,1,0,0,0.0,0,591,2022-09-16,"[MetaInstagram, OrganicSEO, MetaFacebook, Emai...",0

In [572]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty

**Per week aggregations**

In [573]:
new_ads_df['date']=pd.to_datetime(new_ads_df['date'])

In [574]:
new_ads_df['date_weekly']=new_ads_df['date'].dt.to_period('W')

In [575]:
new_ads_df['date_weekly']=new_ads_df['date_weekly'].dt.to_timestamp()

In [576]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective,date_weekly
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty,2021-12-27
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch,2021-12-27
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting,2021-12-27
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation,2021-12-27
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty,2021-12-27

**`CPM,CTR and ROAS`per week**

In [585]:
weekly_cpm_ctr_roas=new_ads_df.groupby(['date_weekly','channel_campaign_objective']).agg( {
    'new_spend_KES': 'sum',
    'new_impressions': 'sum',
    'revenue_KSH': 'sum',
    'new_clicks': 'sum',
    'new_conversions':'sum'
} ).reset_index()

weekly_cpm_ctr_roas=weekly_cpm_ctr_roas.rename(columns={'new_spend_KES':'weekly_spend_KES','new_impressions':'weekly_impressions','revenue_KSH':'weekly_revenue_KES','new_clicks': 'weekly_clicks','new_conversions':'weekly_conversions'})

In [586]:
weekly_cpm_ctr_roas

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1
...,...,...,...,...,...,...,...
6797,2024-12-30,SMS_Retargeting,15069,16416,45998.05,38,1
6798,2024-12-30,TikTokAds_ProductLaunch,6958,7638,25871.10,25,2
6799,2024-12-30,TikTokAds_SeasonalSale,7241,7533,0.00,24,0
6800,2024-12-30,YouTubeAds_Retargeting,6264,6883,0.00,27,0
6801,2024-12-30,YouTubeAds_SeasonalSale,9269,9371,0.00,11,0

**Calculating `weekly(CPM,ctr,roas)`based on `channel_campaign_objective`column**

In [587]:
weekly_cpm_ctr_roas['weekly_cpm']=(weekly_cpm_ctr_roas['weekly_impressions'] / 1000)
weekly_cpm_ctr_roas['weekly_ctr']=((weekly_cpm_ctr_roas['weekly_clicks'] / weekly_cpm_ctr_roas['weekly_impressions']) *100 )
weekly_cpm_ctr_roas['weekly_roas']=weekly_cpm_ctr_roas['weekly_revenue_KES'] / weekly_cpm_ctr_roas['weekly_spend_KES']

In [588]:
weekly_cpm_ctr_roas

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0,6.638,0.165713,0.000000
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0,8.921,0.100886,0.000000
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368
...,...,...,...,...,...,...,...,...,...,...
6797,2024-12-30,SMS_Retargeting,15069,16416,45998.05,38,1,16.416,0.231481,3.052495
6798,2024-12-30,TikTokAds_ProductLaunch,6958,7638,25871.10,25,2,7.638,0.327311,3.718181
6799,2024-12-30,TikTokAds_SeasonalSale,7241,7533,0.00,24,0,7.533,0.318598,0.000000
6800,2024-12-30,YouTubeAds_Retargeting,6264,6883,0.00,27,0,6.883,0.392271,0.000000
6801,2024-12-30,YouTubeAds_SeasonalSale,9269,9371,0.00,11,0,9.371,0.117383,0.000000

In [589]:
new_ads_df['channel'].nunique()

10

In [590]:
new_ads_df['campaign_name'].nunique()

2153

In [591]:
new_ads_df['channel_campaign_objective'].nunique()

60

**Attribution Modelling....**

**A) `Markov Chain Attribution Model`**

**Building proper paths**

In [592]:
def build_path(row):
    path = ["START"] + row['journey_path']
    
    if row['converted'] == 1:
        path.append("CONVERSION")
    else:
        path.append("NULL")
    
    return path

customers_journey_path['path'] = customers_journey_path.apply(build_path, axis=1)

In [593]:
customers_journey_path.head()

,customer_id,journey_path,converted,path
0,CUS000001,"[YouTubeAds, GoogleSearch, TikTokAds, YouTubeAds]",0,"[START, YouTubeAds, GoogleSearch, TikTokAds, Y..."
1,CUS000002,"[MetaInstagram, OrganicSEO, MetaFacebook, Emai...",0,"[START, MetaInstagram, OrganicSEO, MetaFaceboo..."
2,CUS000003,"[TikTokAds, YouTubeAds, EmailCampaign, SMS, Em...",1,"[START, TikTokAds, YouTubeAds, EmailCampaign, ..."
3,CUS000004,"[GoogleSearch, SMS, MetaFacebook, MetaInstagra...",1,"[START, GoogleSearch, SMS, MetaFacebook, MetaI..."
4,CUS000005,"[MetaInstagram, GoogleSearch, OrganicSEO, Meta...",0,"[START, MetaInstagram, GoogleSearch, OrganicSE..."

In [594]:
customers_journey_path['path'].iloc[1]

['START',
 'MetaInstagram',
 'OrganicSEO',
 'MetaFacebook',
 'EmailCampaign',
 'Influencer',
 'GoogleDisplay',
 'EmailCampaign',
 'EmailCampaign',
 'OrganicSEO',
 'MetaFacebook',
 'EmailCampaign',
 'NULL']

**Creating transition counts**

In [595]:
from collections import defaultdict

transition_counts = defaultdict(int)

for path in customers_journey_path['path']:
    for i in range(len(path) - 1):
        transition_counts[(path[i], path[i+1])] += 1

**Converting transition counts to transition probabilities**

In [596]:
df_transitions = pd.DataFrame([
    {'from': k[0], 'to': k[1], 'count': v}
    for k, v in transition_counts.items()
])

df_transitions['prob'] = df_transitions.groupby('from')['count'].transform(lambda x: x / x.sum())

df_transitions

              from            to  count      prob
0            START    YouTubeAds   1468  0.099647
1       YouTubeAds  GoogleSearch   2504  0.093545
2     GoogleSearch     TikTokAds   2477  0.092325
3        TikTokAds    YouTubeAds   2569  0.095325
4       YouTubeAds          NULL    709  0.026487
..             ...           ...    ...       ...
125  GoogleDisplay          NULL    740  0.027453
126  MetaInstagram          NULL    721  0.027051
127     Influencer          NULL    765  0.028765
128     Influencer    CONVERSION    740  0.027825
129   MetaFacebook          NULL    705  0.026313

[130 rows x 4 columns]

**Building transition matrix**

In [597]:
states = list(set(df_transitions['from']).union(set(df_transitions['to'])))

matrix = pd.DataFrame(0, index=states, columns=states)

for _, row in df_transitions.iterrows():
    matrix.loc[row['from'], row['to']] = row['prob']

/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09964702688026066' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09354453078302451' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09232546870923254' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02648684997011357' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09896823241922346' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09406070611188234' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09307902724172819' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09390512447281006' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09274298216338488' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09441624365482233' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.09459710015945415' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']
/tmp/ipykernel_4162/1932105526.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.028327017596518216' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[row['from'], row['to']] = row['prob']

**Computing Baseline Conversion Probability (Simulation)**

In [598]:
def simulate(matrix, n_sim=10000):
    conversions = 0
    
    for _ in range(n_sim):
        current = "START"
        
        while current not in ["CONVERSION", "NULL"]:
            probs = matrix.loc[current]
            
            if probs.sum() == 0:
                break
            
            next_state = random.choices(probs.index, weights=probs.values)[0]
            current = next_state
        
        if current == "CONVERSION":
            conversions += 1
    
    return conversions / n_sim

baseline_conversion_rate = simulate(matrix)

In [599]:
baseline_conversion_rate

0.5074

**Removal Effect (Core Attribution Logic)**

In [600]:
def remove_channel(matrix, channel):
    new_matrix = matrix.copy()
    
    # Remove channel
    new_matrix.loc[channel, :] = 0
    new_matrix.loc[:, channel] = 0
    
    # Re-normalize probabilities
    new_matrix = new_matrix.div(new_matrix.sum(axis=1), axis=0).fillna(0)
    
    return new_matrix

**Computing removal effects:**

In [601]:
removal_effects = {}

for channel in matrix.index:
    if channel in ["START", "CONVERSION", "NULL"]:
        continue
    
    modified_matrix = remove_channel(matrix, channel)
    new_conversion_rate = simulate(modified_matrix)
    
    effect = (baseline_conversion_rate - new_conversion_rate) / baseline_conversion_rate
    removal_effects[channel] = effect

In [602]:
removal_effects

{'YouTubeAds': -0.0003941663381948936,
 'OrganicSEO': 0.00729207725660214,
 'EmailCampaign': 0.012416239653133569,
 'SMS': 0.0013795821836813619,
 'GoogleDisplay': 0.000985415845486687,
 'TikTokAds': -0.007094994087505022,
 'MetaFacebook': 0.0015766653527786991,
 'GoogleSearch': -0.00867165944028394,
 'Influencer': -0.010248324793062638,
 'MetaInstagram': -0.0017737485218762554}

**Attribution Scores**

**Comverting all dicts to a dataFrame**

In [603]:
df_results=pd.DataFrame({
    'channel': list(removal_effects.keys()),
    'removal_effect': list(removal_effects.values()),
})

In [604]:
df_results['total_effect']=sum(removal_effects.values())

In [605]:
df_results['attribution_fraction']= (df_results['removal_effect'] / df_results['total_effect'])

df_results['attribution_percentage']=(df_results['attribution_fraction'] * 100)

In [606]:
df_results=df_results.sort_values(by='attribution_percentage',ascending=False).reset_index()
df_results=df_results.drop(columns=['total_effect','index'])
df_results

         channel  removal_effect  attribution_fraction  attribution_percentage
0     Influencer       -0.010248              2.260870              226.086957
1   GoogleSearch       -0.008672              1.913043              191.304348
2      TikTokAds       -0.007095              1.565217              156.521739
3  MetaInstagram       -0.001774              0.391304               39.130435
4     YouTubeAds       -0.000394              0.086957                8.695652
5  GoogleDisplay        0.000985             -0.217391              -21.739130
6            SMS        0.001380             -0.304348              -30.434783
7   MetaFacebook        0.001577             -0.347826              -34.782609
8     OrganicSEO        0.007292             -1.608696             -160.869565
9  EmailCampaign        0.012416             -2.739130             -273.913043

In [607]:
#df_results.to_csv('Markov_attribution_data.csv')

**`B.)ROI Prediction Model (Ridge/Lasso Regression)`**

In [608]:
weekly_cpm_ctr_roas

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0,6.638,0.165713,0.000000
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0,8.921,0.100886,0.000000
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368
...,...,...,...,...,...,...,...,...,...,...
6797,2024-12-30,SMS_Retargeting,15069,16416,45998.05,38,1,16.416,0.231481,3.052495
6798,2024-12-30,TikTokAds_ProductLaunch,6958,7638,25871.10,25,2,7.638,0.327311,3.718181
6799,2024-12-30,TikTokAds_SeasonalSale,7241,7533,0.00,24,0,7.533,0.318598,0.000000
6800,2024-12-30,YouTubeAds_Retargeting,6264,6883,0.00,27,0,6.883,0.392271,0.000000
6801,2024-12-30,YouTubeAds_SeasonalSale,9269,9371,0.00,11,0,9.371,0.117383,0.000000

**Weekly CPA**

In [609]:
# if weekly conversions is 0 then automatically set weekly_cpa to 0 to prevent 'inf' value...
weekly_cpm_ctr_roas['weekly_cpa']=np.where(weekly_cpm_ctr_roas['weekly_conversions']==0,0,weekly_cpm_ctr_roas['weekly_spend_KES'] /weekly_cpm_ctr_roas['weekly_conversions'])

In [610]:
weekly_cpm_ctr_roas.head()

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas,weekly_cpa
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0,6.638,0.165713,0.000000,0.0
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000,0.0
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0,8.921,0.100886,0.000000,0.0
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000,0.0
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368,3890.0

**Concate this with the `new_ads data`**

In [611]:
weekly_cpm_ctr_roas['date_weekly_cco']=weekly_cpm_ctr_roas['date_weekly'].astype(str) +'_' + weekly_cpm_ctr_roas['channel_campaign_objective']

In [612]:
weekly_cpm_ctr_roas.head()

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas,weekly_cpa,date_weekly_cco
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0,6.638,0.165713,0.000000,0.0,2021-12-27_EmailCampaign_BrandAwareness
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000,0.0,2021-12-27_EmailCampaign_Loyalty
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0,8.921,0.100886,0.000000,0.0,2021-12-27_GoogleDisplay_BrandAwareness
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000,0.0,2021-12-27_GoogleDisplay_ProductLaunch
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368,3890.0,2021-12-27_GoogleSearch_Loyalty

In [613]:
weekly_cpm_ctr_roas=weekly_cpm_ctr_roas.set_index('date_weekly_cco')

In [614]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective,date_weekly
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty,2021-12-27
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch,2021-12-27
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting,2021-12-27
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation,2021-12-27
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty,2021-12-27

In [615]:
#adding same column to new_ads_data for mapping
new_ads_df['date_weekly_cco']=new_ads_df['date_weekly'].astype(str) +'_' + new_ads_df['channel_campaign_objective']

In [616]:
new_ads_df['weekly_spend_KES']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_spend_KES'])
new_ads_df['weekly_impressions']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_impressions'])
new_ads_df['weekly_revenue_KES']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_revenue_KES'])
new_ads_df['weekly_clicks']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_clicks'])
new_ads_df['weekly_conversions']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_conversions'])
new_ads_df['weekly_cpm']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_cpm'])
new_ads_df['weekly_ctr']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_ctr'])
new_ads_df['weekly_roas']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_roas'])
new_ads_df['weekly_cpa']=new_ads_df['date_weekly_cco'].map(weekly_cpm_ctr_roas['weekly_cpa'])

In [617]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,...,date_weekly_cco,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas,weekly_cpa
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,...,2021-12-27_GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368,3890.0
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,...,2021-12-27_GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000,0.0
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,...,2021-12-27_MetaFacebook_Retargeting,8256,8670,22153.08,7,1,8.670,0.080738,2.683270,8256.0
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,...,2021-12-27_MetaInstagram_LeadGeneration,8221,8614,0.00,8,0,8.614,0.092872,0.000000,0.0
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,...,2021-12-27_EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000,0.0

In [618]:
new_ads_df.columns

Index(['date', 'channel', 'channel_campaign_objective', 'campaign_name',
       'new_spend_KES', 'new_impressions', 'new_clicks', 'new_conversions',
       'revenue_KSH', 'new_ctr', 'new_cpc_KES', 'new_roas', 'target_region',
       'campaign_objective', 'date_weekly', 'date_weekly_cco',
       'weekly_spend_KES', 'weekly_impressions', 'weekly_revenue_KES',
       'weekly_clicks', 'weekly_conversions', 'weekly_cpm', 'weekly_ctr',
       'weekly_roas', 'weekly_cpa'],
      dtype='object')

**Modelling Data**

In [619]:
ads_modelling_data=new_ads_df[['date','channel','campaign_objective',
       'new_spend_KES', 'new_impressions', 'new_clicks',
       'weekly_revenue_KES', 'new_ctr', 'target_region',
       'weekly_spend_KES', 'weekly_impressions',
       'weekly_clicks', 'weekly_cpm', 'weekly_ctr','weekly_cpa']]

In [620]:
ads_modelling_data.head()

,date,channel,campaign_objective,new_spend_KES,new_impressions,new_clicks,weekly_revenue_KES,new_ctr,target_region,weekly_spend_KES,weekly_impressions,weekly_clicks,weekly_cpm,weekly_ctr,weekly_cpa
0,2022-01-01,Google Search,Loyalty,3890,4133,4,30580.72,0.096782,South Africa,3890,4133,4,4.133,0.096782,3890.0
1,2022-01-01,Google Display,Product Launch,8420,8505,8,0.00,0.094062,Kenya,8420,8505,8,8.505,0.094062,0.0
2,2022-01-01,Meta Facebook,Retargeting,8256,8670,7,22153.08,0.080738,Egypt,8256,8670,7,8.670,0.080738,8256.0
3,2022-01-01,Meta Instagram,Lead Generation,8221,8614,8,0.00,0.092872,Tanzania,8221,8614,8,8.614,0.092872,0.0
4,2022-01-01,Email Campaign,Loyalty,6802,7434,6,0.00,0.080710,Ghana,6802,7434,6,7.434,0.080710,0.0

In [621]:
ads_modelling_data['date'].describe()

count                            10960
mean     2023-07-02 11:59:59.999999744
min                2022-01-01 00:00:00
25%                2022-10-01 18:00:00
50%                2023-07-02 12:00:00
75%                2024-04-01 06:00:00
max                2024-12-31 00:00:00
Name: date, dtype: object

In [622]:
from sklearn.linear_model import Ridge, Lasso,LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [623]:
sc=StandardScaler()

In [624]:
x=ads_modelling_data.drop(columns=['weekly_revenue_KES','date'])
y=ads_modelling_data['weekly_revenue_KES']
x=pd.get_dummies(x,drop_first=True)

In [625]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,shuffle=False) #shuffling is false to ensure time based splitting....

x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.fit_transform(x_test)
y_train_scaled=np.log1p(y_train)
y_test_scaled=np.log1p(y_test)

In [626]:
ridge_model=Ridge(random_state=42)

In [627]:
ridge_model.fit(x_train_scaled,y_train_scaled)

Ridge(random_state=42)

In [628]:
ridge_preds=ridge_model.predict(x_test_scaled)
ridge_pred_real = np.expm1(ridge_preds)
y_true_real = np.expm1(y_test_scaled)

In [629]:
rmse_ridge=root_mean_squared_error(y_test_scaled,ridge_preds)
rsquared_ridge=r2_score(y_test_scaled,ridge_preds)

real_rmse_ridge=root_mean_squared_error(y_true_real,ridge_pred_real)
real_rsquared_ridge=r2_score(y_true_real,ridge_pred_real)

print('RMSE for ridge_model is:', rmse_ridge)
print('R2_score for ridge_model is:', rsquared_ridge)

print('\n ------------------------------------------------')

print('Real RMSE for ridge_model is:', real_rmse_ridge)
print('Real R2_score for ridge_model is:', real_rsquared_ridge)

RMSE for ridge_model is: 3.6077105945240366
R2_score for ridge_model is: 0.3130152843135581

 ------------------------------------------------
Real RMSE for ridge_model is: 5641670.467521368
Real R2_score for ridge_model is: -15839.387449794305

**MODEL 2**

In [630]:
lasso_model=Lasso(random_state=42)

In [631]:
lasso_model.fit(x_train_scaled,y_train_scaled)

Lasso(random_state=42)

In [632]:
lasso_preds=lasso_model.predict(x_test_scaled)

lasso_pred_real = np.expm1(lasso_preds)

In [633]:
rmse_lasso=root_mean_squared_error(y_test_scaled,lasso_preds)
rsquared_lasso=r2_score(y_test_scaled,ridge_preds)

real_rmse_lasso=root_mean_squared_error(y_true_real,lasso_pred_real)
real_rsquared_lasso=r2_score(y_true_real,lasso_pred_real)

print('RMSE for lasso_model is:',rmse_lasso)
print('R2_score for lasso_model is:', rsquared_lasso)

print('\n ------------------------------------------------')
print('Real RMSE for lasso_model is:',real_rmse_lasso)
print('Real R2_score for lasso_model is:', real_rsquared_lasso)

RMSE for lasso_model is: 3.8169027872374635
R2_score for lasso_model is: 0.3130152843135581

 ------------------------------------------------
Real RMSE for lasso_model is: 91810.61603121895
Real R2_score for lasso_model is: -3.195040640019812

**Model 3:**

In [634]:
lr=LinearRegression()

In [635]:
lr.fit(x_train_scaled,y_train_scaled)

LinearRegression()

In [636]:
lr_preds=lr.predict(x_test_scaled)

lr_pred_real = np.expm1(lr_preds)

In [637]:
rmse_lr=root_mean_squared_error(y_test_scaled,lr_preds)
rsquared_lr=r2_score(y_test_scaled,lr_preds)

real_rmse_lr=root_mean_squared_error(y_true_real,lr_pred_real)
real_rsquared_lr=r2_score(y_true_real,lr_pred_real)

print('RMSE for lasso_model is:',rmse_lr)
print('R2_score for lasso_model is:', rsquared_lr)

print('\n ------------------------------------------------')
print('Real RMSE for lr_model is:',real_rmse_lr)
print('Real R2_score for lr_model is:', real_rsquared_lr)

RMSE for lasso_model is: 3.607804568761211
R2_score for lasso_model is: 0.3129794944663763

 ------------------------------------------------
Real RMSE for lr_model is: 5673072.855722459
Real R2_score for lr_model is: -16016.218185606129

**Model 4**

In [638]:
rf=RandomForestRegressor(random_state=42, max_depth=10,
    min_samples_leaf=5,
    n_estimators=200)

In [639]:
rf.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=5, n_estimators=200,
                      random_state=42)

**train evaluation**

In [640]:
rf_train_preds=rf.predict(x_train)

In [641]:
rmse_rf_train=root_mean_squared_error(y_train,rf_train_preds)
rsquared_rf_train=r2_score(y_train,rf_train_preds)

print('RMSE for rf_model_train is:',rmse_rf_train)
print('R2_score for rf_model_train is:', rsquared_rf_train)

RMSE for rf_model_train is: 13816.313237734472
R2_score for rf_model_train is: 0.9067900760711646

**test evaluation**

In [642]:
rf_preds=rf.predict(x_test)

In [643]:
rmse_rf=root_mean_squared_error(y_test,rf_preds)
rsquared_rf=r2_score(y_test,rf_preds)

print('RMSE for rf_model_test is:',rmse_rf)
print('R2_score for rf_model_test is:', rsquared_rf)

RMSE for rf_model_test is: 20307.3181436537
R2_score for rf_model_test is: 0.7947630674763752

In [644]:
ads_modelling_data['weekly_revenue_KES'].describe()

count     10960.000000
mean      47129.517057
std       45171.215303
min           0.000000
25%        8340.330000
50%       38680.735000
75%       72395.780000
max      323949.400000
Name: weekly_revenue_KES, dtype: float64

**FEATURE IMPORTANCE**

In [645]:
importances=rf.feature_importances_

In [646]:
df_importances=pd.DataFrame({'features': x.columns ,'importances':importances}).sort_values(by='importances',ascending=False).reset_index().drop('index',axis=1)

In [647]:
#df_importances.to_csv('drives_of_prediction_with_cpa.csv')
df_importances
#df_importances.to_csv('drives_of_prediction_without_cpa.csv')

                              features  importances
0                           weekly_cpa     0.643951
1                     weekly_spend_KES     0.179401
2                   weekly_impressions     0.059757
3                           weekly_cpm     0.051710
4                        weekly_clicks     0.030519
5                           weekly_ctr     0.011987
6                              new_ctr     0.002641
7                        new_spend_KES     0.002358
8                      new_impressions     0.002301
9                           new_clicks     0.002212
10   campaign_objective_Product Launch     0.001162
11                 channel_Organic SEO     0.001160
12               channel_Google Search     0.001152
13      campaign_objective_Retargeting     0.001080
14  campaign_objective_Lead Generation     0.001006
15    campaign_objective_Seasonal Sale     0.000938
16                         channel_SMS     0.000885
17          campaign_objective_Loyalty     0.000862
18                 channel_YouTube Ads     0.000786
19              channel_Meta Instagram     0.000686
20                  channel_TikTok Ads     0.000567
21                  channel_Influencer     0.000508
22              channel_Google Display     0.000472
23               channel_Meta Facebook     0.000403
24                 target_region_Ghana     0.000310
25                target_region_Uganda     0.000288
26                 target_region_Kenya     0.000242
27               target_region_Nigeria     0.000186
28              target_region_Ethiopia     0.000173
29              target_region_Tanzania     0.000167
30          target_region_South Africa     0.000131

**Assessing the dataFrames used for code executions**

In [648]:
ads.head()

,date,channel,campaign_name,spend_KES,impressions,clicks,conversions,revenue_KES,ctr,cpc_KES,roas,target_region,campaign_objective
0,2022-01-01,Google Search,Seasonal_Sale_Jan2022,48481.83,4969763,162744,10929,4.862628e+07,3.2747,0.30,1002.979,South Africa,Loyalty
1,2022-01-01,Google Display,Loyalty_Jan2022,25996.75,3788402,300427,41827,3.235644e+08,7.9302,0.09,12446.337,Kenya,Product Launch
2,2022-01-01,Meta Facebook,Brand_Awareness_Jan2022,6293.25,871175,36745,3968,2.007122e+07,4.2179,0.17,3189.327,Egypt,Retargeting
3,2022-01-01,Meta Instagram,Brand_Awareness_Jan2022,6825.99,816764,39761,3768,2.255018e+07,4.8681,0.17,3303.576,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,Loyalty_Jan2022,18078.55,1875414,124779,10767,3.427620e+07,6.6534,0.14,1895.960,Ghana,Loyalty

In [649]:
customers.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,converted,conversion_value_KES,duplicate_conversion
0,JRN0000001,CUS014969,1,1,Google Search,NaN,2022-06-28 11:51:05,1,1,0,0.0,0
1,JRN0000002,CUS000530,1,1,Influencer,NaN,2023-05-14 08:09:01,1,1,0,0.0,0
2,JRN0000003,CUS012098,1,6,Email Campaign,NaN,2023-08-31 04:12:05,1,0,0,0.0,0
3,JRN0000003,CUS012098,2,6,YouTube Ads,Email Campaign,2023-09-01 06:12:05,0,0,0,0.0,0
4,JRN0000003,CUS012098,3,6,Meta Facebook,YouTube Ads,2023-09-04 22:12:05,0,0,0,0.0,0

In [650]:
customers_copy=customers_copy.drop(columns=['converted_x','converted_y','touch_timestamp_day','duplicate_conversion','journey_path'])

In [651]:
customers_copy.to_csv('modified_customers_data.csv')
customers_copy.head()

,journey_id,customer_id,touchpoint_order,touchpoint_total,channel,previous_channel,touch_timestamp,is_first_touch,is_last_touch,conversion_value_KES,conversions_window_days
0,JRN0006398,CUS000001,1,4,YouTubeAds,N/A,2024-11-04 04:51:08,1,0,0.0,3
1,JRN0006398,CUS000001,2,4,GoogleSearch,YouTube Ads,2024-11-06 11:51:08,0,0,0.0,3
2,JRN0006398,CUS000001,3,4,TikTokAds,Google Search,2024-11-06 20:51:08,0,0,0.0,3
3,JRN0006398,CUS000001,4,4,YouTubeAds,TikTok Ads,2024-11-07 04:51:08,0,1,0.0,3
4,JRN0006793,CUS000002,1,3,MetaInstagram,N/A,2022-09-16 14:50:21,1,0,0.0,591

In [652]:
weekly_cpm_ctr_roas.head()
weekly_cpm_ctr_roas=weekly_cpm_ctr_roas.reset_index()
weekly_cpm_ctr_roas.drop(columns=['date_weekly_cco'])

,date_weekly,channel_campaign_objective,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas,weekly_cpa
0,2021-12-27,EmailCampaign_BrandAwareness,6201,6638,0.00,11,0,6.638,0.165713,0.000000,0.0
1,2021-12-27,EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000,0.0
2,2021-12-27,GoogleDisplay_BrandAwareness,8608,8921,0.00,9,0,8.921,0.100886,0.000000,0.0
3,2021-12-27,GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000,0.0
4,2021-12-27,GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368,3890.0
...,...,...,...,...,...,...,...,...,...,...,...
6797,2024-12-30,SMS_Retargeting,15069,16416,45998.05,38,1,16.416,0.231481,3.052495,15069.0
6798,2024-12-30,TikTokAds_ProductLaunch,6958,7638,25871.10,25,2,7.638,0.327311,3.718181,3479.0
6799,2024-12-30,TikTokAds_SeasonalSale,7241,7533,0.00,24,0,7.533,0.318598,0.000000,0.0
6800,2024-12-30,YouTubeAds_Retargeting,6264,6883,0.00,27,0,6.883,0.392271,0.000000,0.0
6801,2024-12-30,YouTubeAds_SeasonalSale,9269,9371,0.00,11,0,9.371,0.117383,0.000000,0.0

In [654]:
weekly_cpm_ctr_roas.to_csv('aggregated_weekly_data.csv')

In [655]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,...,date_weekly_cco,weekly_spend_KES,weekly_impressions,weekly_revenue_KES,weekly_clicks,weekly_conversions,weekly_cpm,weekly_ctr,weekly_roas,weekly_cpa
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,...,2021-12-27_GoogleSearch_Loyalty,3890,4133,30580.72,4,1,4.133,0.096782,7.861368,3890.0
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,...,2021-12-27_GoogleDisplay_ProductLaunch,8420,8505,0.00,8,0,8.505,0.094062,0.000000,0.0
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,...,2021-12-27_MetaFacebook_Retargeting,8256,8670,22153.08,7,1,8.670,0.080738,2.683270,8256.0
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,...,2021-12-27_MetaInstagram_LeadGeneration,8221,8614,0.00,8,0,8.614,0.092872,0.000000,0.0
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,...,2021-12-27_EmailCampaign_Loyalty,6802,7434,0.00,6,0,7.434,0.080710,0.000000,0.0

In [656]:
new_ads_df=new_ads_df.drop(columns=['date_weekly','date_weekly_cco','weekly_spend_KES','weekly_impressions','weekly_revenue_KES','weekly_clicks','weekly_conversions','weekly_cpm','weekly_ctr','weekly_roas','weekly_cpa'])

In [657]:
new_ads_df.head()

,date,channel,channel_campaign_objective,campaign_name,new_spend_KES,new_impressions,new_clicks,new_conversions,revenue_KSH,new_ctr,new_cpc_KES,new_roas,target_region,campaign_objective
0,2022-01-01,Google Search,GoogleSearch_Loyalty,GoogleSearch_Loyalty_January_2022,3890,4133,4,1,30580.72,0.096782,972.500000,7.861368,South Africa,Loyalty
1,2022-01-01,Google Display,GoogleDisplay_ProductLaunch,GoogleDisplay_ProductLaunch_January_2022,8420,8505,8,0,0.00,0.094062,1052.500000,0.000000,Kenya,Product Launch
2,2022-01-01,Meta Facebook,MetaFacebook_Retargeting,MetaFacebook_Retargeting_January_2022,8256,8670,7,1,22153.08,0.080738,1179.428571,2.683270,Egypt,Retargeting
3,2022-01-01,Meta Instagram,MetaInstagram_LeadGeneration,MetaInstagram_LeadGeneration_January_2022,8221,8614,8,0,0.00,0.092872,1027.625000,0.000000,Tanzania,Lead Generation
4,2022-01-01,Email Campaign,EmailCampaign_Loyalty,EmailCampaign_Loyalty_January_2022,6802,7434,6,0,0.00,0.080710,1133.666667,0.000000,Ghana,Loyalty

In [658]:
new_ads_df.to_csv('modified_ads_spend_daily.csv')

In [659]:
ads_modelling_data.to_csv('ads_modelling_data.csv')

**The end!!**